server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: pagamento
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pagamento
    username: root
    password: 123456  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
    
crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue
    queue-delete: crud.delete-produto.queue
