server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: 123456  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey
    routingKey-delete: crud.produto.routingKeyDelete
    queue: crud.produto.queue
    queue-delete: crud.delete-produto.queue